version: "3"
services:
  fpm:
    image: registry.dontping.me:5000/deploymyapp_fpm
    environment:
    - STACK
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  nginx:
    image: registry.dontping.me:5000/deploymyapp_nginx
    environment:
    - STACK
    ports:
     - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
